### ISSUE TITLE
Search Parameters

### ISSUE THREAD

**Issue by brigsz** [agrc/ugs-chemistry#35]
I think this covers the parameters needed.  Lets drop country put in HUC

![screen shot 2015-01-07 at 10 00 43 am](https://cloud.githubusercontent.com/assets/6306463/5666190/26d692b4-971b-11e4-938c-8fd0e3e5f54a.png)

**Comment by inkenbrandt** [comment]
For the location selection I would like like an interactive query:
* Click to draw selection polygon
as opposed to the `Point Location` and the `Bounding Box` dialogs in the upper right corner of the WQP site.

* DataSource
* State
* County
* Site Type
* Site ID
* HUC
* Param Group
* Parameter
* Date Range

`Sample Media` will not be necessary, as it will always be water.

**Comment by stdavis** [comment]
@inkenbrandt Can you mark which parameters will be a drop down and which would be a free type text box?

**Comment by stdavis** [comment]
Given our recent chat, please mark them as one of these:
- free type
- drop down (single)
- multiple option

**Comment by stdavis** [comment]
@inkenbrandt Where would I get the list of possible values for the Site Type and Param Group drop downs? Is it a static list?

**Comment by stdavis** [comment]
From @inkenbrandt 
>Param Groups:
>['Information', 'Inorganics, Minor, Metals', 'Inorganics, Major, Metals', 'Stable Isotopes', 'Inorganics, Minor, Non-metals', 'Organics, other', 'Microbiological', 'Biological', 'Nutrient', 'Inorganics, Major, Non-metals', 'Radiochemical', 'Organics, pesticide', 'Organics, PCBs', 'Toxicity', 'Sediment', 'Physical']

>Site Type:
>['Aggregate groundwater use','Aggregate surface-water-use','Facility','Lake, Reservoir, Impoundment','Land','Other Groundwater','Other','Surface Water','Spring','Stream','Subsurface','Well','Wetland']

**Comment by stdavis** [comment]
@inkenbrandt BTW - I love how these are already formatted as arrays for easily copying into my code. :+1:

**Comment by stdavis** [comment]
I put all filters in a table on the wiki just so that we are on the same page: https://github.com/agrc/ugs-chemistry/wiki
