### ISSUE TITLE
General Layout Possibilities

### ISSUE THREAD

**Issue by brigsz** [agrc/ugs-chemistry#36]
This is the general idea, but it just looks like every other site.  I need to look into the graphical output based on query return (lower right corner) Seems like there is work there to figure out the histograms

![screen shot 2015-01-08 at 9 50 30 am](https://cloud.githubusercontent.com/assets/6306463/5666294/d103083a-971b-11e4-924f-940dd701aef8.png)

**Comment by stdavis** [comment]
Closing in favor of #40
