### ISSUE TITLE
Search results grid

### ISSUE THREAD

**Issue by inkenbrandt** [agrc/ugs-chemistry#38]
These are the following I would like to see in the tabular section of the UI. Ideally, we could view both the stations and the results tables via tabs - like what is done in the typical ArcMap interface.

For the `Results` table (aliases are listed):
* `Database Source`
* `Organization Name`
* `Parameter`
* `Parameter Group`
* `Result Measure Value`
* `Sample Date`
* `Sample Media`
* `Station Id`
* `Result Measure Unit`
* `Result Detection Condition`

For the `Stations` table (aliases are listed):
* `Database Source`
* `Monitoring Location Id`
* `Monitoring Location Name`
* `Monitoring Location Type`
* `Organization Name`
* `Latitude`
* `Longitude`
* `DEM Elevation m`
* `Aquifer`
* `Formation Type`
* `Well Depth`
* `WR Well Id`

**Comment by stdavis** [comment]
I like the tabbed table idea.

Not going to be able to fit all of these fields in the two tables. I would suggest not having more than 5 or 6 fields per table if we can help it. Here's an example of the space issues: http://share.flairbuilder.com/?sid=I64FYv95R7

**Comment by inkenbrandt** [comment]
These are the following I would like to see in the tabular section of the UI. Ideally, we could view both the stations and the results tables via tabs - like what is done in the typical ArcMap interface.

For the `Results` table (aliases are listed):
* `Parameter`
* `Result Measure Value`
* `Sample Date`
* `Station Id`
* `Result Measure Unit`
* `Result Detection Condition`

For the `Stations` table (aliases are listed):
* `Database Source`
* `Monitoring Location Id`
* `Monitoring Location Name`
* `Monitoring Location Type`
* `Well Depth`
* `WR Well Id`

**Comment by stdavis** [comment]
That should work.
