### ISSUE TITLE
Parameter Charts

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-chemistry#39]
https://github.com/Esri/cedar

**Comment by steveoh** [comment]
I would also give honorable mention to highcharts and chartist.

**Comment by inkenbrandt** [comment]
Scott and Steve, here are examples of the two types of charts I am interested in including:
https://github.com/inkenbrandt/IPython/blob/master/WQD%20Graphs.ipynb

**Comment by stdavis** [comment]
So awesome. Thanks. Brownie points for using iPython notebook.

On Thu, May 21, 2015 at 3:04 PM, Paul <notifications@github.com> wrote:

> Scott and Steve, here are examples of the two types of charts I am
> interested in including:
> https://github.com/inkenbrandt/IPython/blob/master/WQD%20Graphs.ipynb
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/ugs-chemistry/issues/39#issuecomment-104419723>.
>



-- 
*Scott Davis*
Utah AGRC <http://gis.utah.gov/developer/>
stdavis@utah.gov
@ScottAGRC <https://twitter.com/ScottAGRC>

**Comment by stdavis** [comment]
Charts will show only one parameter at a time. 

Data will be collected from all currently selected stations (may need to put some limit on the number of stations to prevent huge queries).

Basic workflow: http://quick.as/anwrhd7qq
Possible notes to be added: ![image](https://cloud.githubusercontent.com/assets/1326248/7865805/86626598-0528-11e5-9153-5d0e11946995.png)

**Comment by stdavis** [comment]
@inkenbrandt Do you have a list of all of the known parameters? Is this something that's going to be static or do we need to manage a lookup table in the database for it? I ran a summary on this field in the database that I have and got back a lot of junk. Looks like we need to do some normalization in the database seeder.

**Comment by inkenbrandt** [comment]
If it would be easier, we could limit the graphable parameters to a long list.  There are several organic chemicals in the database that do not need to be plotted.

**Comment by stdavis** [comment]
If you can give me a defined list I can populate the drop down with them.

**Comment by inkenbrandt** [comment]
This is where this table comes in:
https://docs.google.com/a/utah.gov/spreadsheets/d/1EY_30rSQxvH2JrVhjVSRzOdyh9nVryA5RbofVZhp0hs/edit?usp=sharing 

I am not sure if the names match the parameters exactly or not.

**Comment by stdavis** [comment]
@inkenbrandt: Is [this table](https://docs.google.com/a/utah.gov/spreadsheets/d/1EY_30rSQxvH2JrVhjVSRzOdyh9nVryA5RbofVZhp0hs/edit?usp=sharing) still the authoritative list of parameters? If so there are a few issues that I can see:
- The "ANALYTE" column has several duplicate values in it (e.g. "Specific conductance" on lines 2 & 20). So if I show that column in the dropdown for the charts the user will not know which one to choose. Should I concat that column with "parm_cd" like this, "Specific conductance (00095)"? Looks like this would result in unique options for the user. They would just have to know the code of the specific param that they are working with.
- The values in the "ANALYTE" column do not exactly match those in `Results:Param` from the app database. You can checkout a unique list of all of the parameters in the app database in the `Params` table. Do we need to normalize those values in [agrc/ugs-db](https://github.com/agrc/ugs-db)? If so we may want to add a code column to the `Results` table and use that for the chart queries to help with performance.

Let me know your thoughts...

**Comment by inkenbrandt** [comment]
That table is waaaay out of date!  I suggest using a unique list of parameters obtained from the `Results:Param` database.  If you need me to winnow that list down for whatever reason, I can do that if you provide the list - I don't have an up-do-date version of the `Results` table.  Would it be easier if the graph function only worked for a subset of the parameters?

**Comment by stdavis** [comment]
Here's the list. It has 1,136 rows. I think that it could use some winnowing for sure.
[Params.csv.zip](https://github.com/agrc/ugs-chemistry/files/55639/Params.csv.zip)

**Comment by inkenbrandt** [comment]
Good deal!  Just to be sure, am I selecting the parameters that the user will be able to graph?

**Comment by stdavis** [comment]
Yes we are deciding what will go in this dropdown box:
![image](https://cloud.githubusercontent.com/assets/1326248/11659818/69123264-9d87-11e5-8e4e-74b28e93e88e.png)

On the other hand, the "Parameter" filter uses a type-ahead that queries the `Params` table rather than a drop down.
![image](https://cloud.githubusercontent.com/assets/1326248/11659891/c14eee4a-9d87-11e5-99ef-3bc5934cb622.png)

I'm not sure why I chose the drop down for the charts. I'm guessing it was because I thought that the number of options for charting would be much smaller. If you wanted it to be a type-ahead like the filter I could do that as well.

**Comment by inkenbrandt** [comment]
I would prefer the type-ahead, if it isn't too much extra effort.

**Comment by stdavis** [comment]
Will do.

**Comment by stdavis** [comment]
@inkenbrandt How do you want `null` values for `ResultValue` treated? Should they be excluded or set to zero?

**Comment by inkenbrandt** [comment]
excluded

**Comment by stdavis** [comment]
@inkenbrandt I'm using [numpy.histogram](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.histogram.html) to calculate the histogram values. How do you want me to choose the number of bins? Or should I be using something that auto-calculates?

**Comment by inkenbrandt** [comment]
I'm pretty sure the bin size is optional with that function, which I assume means that the function will automatically calculate the best bin size.  

Bin size is extremely dependent on sample size.

**Comment by stdavis** [comment]
Looks like it defaults to 10 equal width bins. Does that sound good?

**Comment by inkenbrandt** [comment]
Yeah, I saw that.  It's not going to be pretty.  

Is matplotlib out of the question?  It's the go-to Python graphing library:
http://matplotlib.org/1.2.1/examples/pylab_examples/histogram_demo.html

**Comment by inkenbrandt** [comment]
I think the square root of the number of samples would work well (better than 10).
np.histogram(x, bins=np.sqrt(len(x)))

**Comment by stdavis** [comment]
> excluded

Should I also be excluding values of 0?

**Comment by inkenbrandt** [comment]
Now that I think about it, yes.   Most of the time, these represent nondetects, which is a value higher than 0 but below what the lab equipment can detect.  For the sake of graphing trends, they should be excluded.  This will skew histogram distributions to the left, but it will make for better plots.

**Comment by stdavis** [comment]
Here's an example for Nitrate using the square root of the number of rows as the number of equal width bins:
![image](https://cloud.githubusercontent.com/assets/1326248/11902720/2b08c9e6-a571-11e5-9335-48c434cb131d.png)

This doesn't look very useful to me. Is there a better test? Or do I need to be generating the histogram data differently? I took a look at pyplot and looks like the bins argument behaves the same way as numpy.

**Comment by steveoh** [comment]
Should it be an input the user can set if we can't always give the best default?

**Comment by inkenbrandt** [comment]
Chemistry data are naturally logrithmically distributed, so maybe we can
offer a "transform" option?

On Friday, December 18, 2015, Scott Davis <notifications@github.com> wrote:

> Here's an example for Nitrate using the square root of the number of rows
> as the number of equal width bins:
> [image: image]
> <https://cloud.githubusercontent.com/assets/1326248/11902720/2b08c9e6-a571-11e5-9335-48c434cb131d.png>
>
> This doesn't look very useful to me. Is there a better test? Or do I need
> to be generating the histogram data differently? I took a look at pyplot
> and looks like the bins argument behaves the same way as numpy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agrc/ugs-chemistry/issues/39#issuecomment-165846943>.
>


-- 
Paul Inkenbrandt, P.G.
Project Geologist
Utah Geological Survey
1594 W. North Temple, Suite 3110
Salt Lake City, Utah 84114-6100
Ph: (801) 537-3361
Cell: (435) 881-2816
Fax: (801) 537-3400

**Comment by steveoh** [comment]
Does that mean you would prefer the y axis to be logarithmic? Or what do you mean by transform?

**Comment by inkenbrandt** [comment]
Sorry for the brevity. I was messaging from my phone.  The transform would require the log of each value:
```
transformedXvalues = [numpy.log(x[i]) for i in range(len(x))]

```

**Comment by stdavis** [comment]
So here's a few different options all using the number of bins as the sqrt of the total number of values:

This is for Kane county stations.

log(y values)
![image](https://cloud.githubusercontent.com/assets/1326248/11940333/376a9c0c-a7e5-11e5-9e89-98cf6b191331.png)

logarithmic y axis (option when building the chart)
![image](https://cloud.githubusercontent.com/assets/1326248/11940343/45c51cb4-a7e5-11e5-90fc-fb84fd8c9a2f.png)

No changes to values or axis for comparison
![image](https://cloud.githubusercontent.com/assets/1326248/11940347/4fd4d118-a7e5-11e5-8eda-4d337eab80b1.png)

log(y values) looks the most useful to me but I'm not a scientist. :)

Would the logging of y values be something that we do all of the time or would it be an optional transform to apply when choosing the chart options? If you want it to be a checkbox what should the label read?

**Comment by inkenbrandt** [comment]
In the histogram, the y-axis represents the count of values for each bin. Each bin represents a range of concentration values.  If done, the transformation should be conducted along the x-axis, and not the y.  Because we have no interest in stretching out the bins, we instead apply a function to the values of the data before they are plotted.  However, if this is too complicated, then we can leave the data untransformed when plotting.

**Comment by inkenbrandt** [comment]
Ideally, the log(values) would be an option, because some data, like temperature, are not logarithmically distributed.
