### ISSUE TITLE
Security for SDWIS features

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-chemistry#41]
All SDWIS data should require a login.

Default AGRC user management setup.

**Comment by stdavis** [comment]
Yes/No access. Mark Jensen should be admin in addition to Paul.

Default login link to request access. Don't advertise the missing SDWIS data. General use won't care about it. Only for higher level users.

**Comment by stdavis** [comment]
Closed by accident.

**Comment by stdavis** [comment]
@inkenbrandt: I'm assuming that you want Deidre Beck in place on Mark Jensen on this?

**Comment by inkenbrandt** [comment]
Yes!
