### ISSUE TITLE
Make ParameterGroup query select via AND or OR

### ISSUE THREAD

**Issue by inkenbrandt** [agrc/ugs-chemistry#47]
Right now, the `ParameterGroup` query uses an SQL `IN` condition, which is a compact representation of a long `OR` query. When the user selects multiple parameters, then the query returns all samples containing any of those parameters. For example, if I select  `Organics, Other` and `Nutrients`, the query will return all `Stations` related to `Results` that have `Organics, Other` <b>OR</b> `Nutrients` (i.e. this is an inclusive query). 

I suggest either:
* adding a check box that allows the user to alternate between `AND` and `OR` queries, or
* making the query select via an `AND` query - show `Stations` related to `Results` that have this <b>AND</b> this (an exclusive query).

The other queries function properly in regards to this, as you cannot have a station in `Cache` and `Weber` county, etc.

While this may seem like a trivial aspect of this tool, it will be very useful for the end user.

**Comment by stdavis** [comment]
@inkenbrandt What do you think about something like this?
![image](https://cloud.githubusercontent.com/assets/1326248/7025409/adcbbe2c-dd00-11e4-8180-4622f9c39a9e.png)

The toggle buttons could be configured to only show up for filters that they are appropriate for.

My only worry is that the any/all words may not be clear to the user what they are for. We could add a tooltip to them that says something like "show results that include any of these options".

**Comment by stdavis** [comment]
@inkenbrandt Can you send me an example of your preferred AND type query?

**Comment by inkenbrandt** [comment]
@stdavis The any/all functionality with tooltips would work great!  I really like the look of it.  The parameter groups would be the only query I would be interested in having for this type of selection.

The query might be too complicated.  I am pretty sure SQL can handle it, I just don't know how to write the query.  

Each `Result` row has `SampleId`. The `SampleId` identifies each individual sampling instance.  For example, every time I go out and collect a water sample, I fill up multiple sample bottles. Each bottle I fill essentially represents a `ParamGroup`, and all of those bottles would have the same `SampleId` because they were all collected at the same time and place.  As I said, each bottle I sampled has water in it that represents a `ParamGroup`, which contains multiple parameters.  When I fill up a `Nutrients` bottle and send it to the lab, they send me a sheet of `Nutrients` results that contained a row for `Nitrate` and a row for `Ammonia`.  I want to find the `Stations` that contain `Results` where those `Results` have the specified parameters with a matching `SampleId`

The `AND` query would select `Stations` that have `Results` with the same `SampleId` and that have the `ParamGroup` that meet the specifications. 

![image](https://cloud.githubusercontent.com/assets/7726565/7046481/48cc8510-ddc3-11e4-802a-9d71739278d5.png)

Look at the image above.  If we chose `Physical` AND `Inorganics, Major, Non-metals` AND `Nutrient` AND `Inorganics, Minor, Metals` AND `Inorganics, Major, Metals`, then the query would return the selected `Station` `USGS-09380000`.  However, if we added `Stable Isotopes`, then the station would no longer be selected.

I will try my best to work up the query language, but we might have to nix this option for the sake of simplicity.

**Comment by stdavis** [comment]
@inkenbrandt The branch with the any/all buttons is pushed to the test server: http://test.mapserv.utah.gov/ugschemistry/

Includes popups and is wired up with the new queries. When you get a minute take a look and if you're happy with it I'll merge back into master and move on.

**Comment by stdavis** [comment]
Closed with 644ec1f33cd877b8e66743e61ddd184e447b2b31
