### ISSUE TITLE
Click to select station and associated results

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-chemistry#53]
The user should be able to click on a station to select it. This would filter the data in the grid to show only the data associated with that station while still honoring any existing filters. The user could then click on the map (not on a station) to clear the selection or click on a "clear selection" button on the grid. The "clear selection" button would only appear if a station is selected.

@inkenbrandt: Do we need to allow for multiple stations to be selected?

**Comment by inkenbrandt** [comment]
The select by click doesn't need to do multiple stations. I think the other queries already accommodate for selecting multiple stations.
