### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-chemistry#54]
Users will be able to choose between "KML + CSV" or "Shapefile + CSV". After the download is complete a link to a `.zip` file will be presented.

The download link could open a dialog or another tab. I'm thinking the tab would be nice as it could allow the user to continue to use the site when the download is being generated. We would just need to make sure that there is a visual cue on the tab that alerts the user when the download is ready.

**Comment by stdavis** [comment]
@inkenbrandt: Does this issue look correct to you?

**Comment by inkenbrandt** [comment]
Is there a going to be a pure CSV option?

**Comment by stdavis** [comment]
Sure, we can do that. So maybe the choices should look like this?
- KML (Stations) + CSV (Results)
- Shapefile (Stations) + CSV (Results)
- CSV (Stations and Results)

**Comment by inkenbrandt** [comment]
That's great!
