### ISSUE TITLE
Adjustable grid height

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-chemistry#62]

**Comment by steveoh** [comment]
if you are using dgrid you can use the [auto-height](https://github.com/SitePen/dgrid/blob/master/doc/usage/Styling-dgrid.md#the-dgrid-autoheight-class) class.

**Comment by stdavis** [comment]
The docs say that the dgrid auto-height class makes the grid adjust its size to its contents. Not sure how that is helpful but maybe I'm missing something.
