### ISSUE TITLE
Add Additional Base Maps

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-chemistry#71]
From Marshall R:
These are the three basemaps we want to add: Bing (default), topo, and streets.

Here is the Bingmaps code w/key I use for my apps:

this goes in the require: 
"esri/virtualearth/VETiledLayer"

and the variable: 
bing = new esri.virtualearth.VETiledLayer({
          bingMapsKey: "Aj2_MrokUlw0z5rag980VdzHspXlva8DFM-rUnbPBNcnSrUvlin39XD1ZRt83Ycb",
          mapStyle: esri.virtualearth.VETiledLayer.MAP_STYLE_AERIAL_WITH_LABELS
        });
	map.addLayer(bing);

Streets url: http://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer

Topo url: http://server.arcgisonline.com/ArcGIS/rest/services/USA_Topo_Maps/MapServer

**Comment by stdavis** [comment]
@inkenbrandt: Our layer-selector doesn't support the VETiledLayer types so we can't do Bing for now. Not sure why you would want that over the state's google imagery ("Hybrid") except maybe for areas outside the state boundaries? I'm guessing that the google imagery is much more up-to-date.

Also, AGRC has a Topo basemap so I just used ours. I did add the ESRI streets basemap.

**Comment by inkenbrandt** [comment]
That's good Scott.  We just need a default that covers multiple states to make the editorial people happy with it.  The other options can be AGRC.  I like the AGRC topo.

**Comment by stdavis** [comment]
OK. I'll make the ESRI streets basemap the default...
