### ISSUE TITLE
Limit displayed data

### ISSUE THREAD

**Issue by stdavis** [agrc/ugs-chemistry#75]
We seen some issues where the map services get overwhelmed. May need to limit the number of stations displayed on the map or the number of results in the tables.

**Comment by inkenbrandt** [comment]
Yes!  We should definitely do this.

**Comment by stdavis** [comment]
@inkenbrandt: What would be an acceptable limit? Or, in other words, what's the highest number of stations that you would ever want to see at once? Just trying to get a ballpark idea of what would be practical.

**Comment by inkenbrandt** [comment]
It could be as small as 3000 sites without hindering most queries. Very rarely do I compile more sites than that.  That will still bring up a huge number of results though. For example, querying the [Water Quality Portal site](http://www.waterqualitydata.us/portal/) for all of Salt Lake and Summit counties will bring up 2700 sites, but those sites have over 1 million results.  We may want to limit results.

**Comment by inkenbrandt** [comment]
Try testing this while logged in for the SDWIS data.  Also try doing query after doing one query and downloading.  I am still seeing serious lag (minutes) with grid population and refresh.
